# Generated by Django 4.2.7 on 2024-02-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('note_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notelist')),
            ],
        ),
    ]
