# Generated by Django 5.0.2 on 2024-02-21 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_photonote'),
    ]

    operations = [
        migrations.AddField(
            model_name='photonote',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
