# Generated by Django 5.0.2 on 2024-02-21 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_photonote_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photonote',
            name='img',
        ),
        migrations.AddField(
            model_name='photonote',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/images/'),
            preserve_default=False,
        ),
    ]
