# Generated by Django 5.0.2 on 2024-02-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_photonote_img_photonote_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonote',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
