# Generated by Django 4.2.3 on 2024-02-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_tasklist_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
