# Generated by Django 4.2.3 on 2024-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_user_profile_picture_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile_pictures/'),
        ),
    ]
